---
engine: knitr
---

::: {.callout-note}
Chapman and Hall/CRC는 2023년 7월에 이 책을 출판했습니다. [여기](https://www.routledge.com/Telling-Stories-with-Data-With-Applications-in-R/Alexander/p/book/9781032134772)에서 구매할 수 있습니다.

이 온라인 버전에는 인쇄된 내용에 대한 몇 가지 업데이트가 있습니다. 인쇄 버전과 일치하는 온라인 버전은 [여기](https://rohanalexander.github.io/telling_stories-published/)에서 볼 수 있습니다.
:::

**추천사**

> 이 깔끔하고 재미있는 책은 통계 커뮤니케이션, 프로그래밍 및 모델링에 대한 광범위한 주제를 다루고 있어 모든 통계 과정이나 자율 학습 프로그램에 유용한 보충 자료가 될 것입니다. 저는 이 책을 정말 좋아합니다!
>
> **앤드류 겔만**, 컬럼비아 대학교, [회귀 및 기타 이야기](https://avehtari.github.io/ROS-Examples/) 저자

> 훌륭한 책입니다. 통계에서 의사소통과 재현성은 점점 더 중요해지고 있으며, 이 책은 이러한 주제 등을 실용적이고 매력적이며 진정으로 독특한 방식으로 다룹니다.
>
> **다니엘라 위튼**, 워싱턴 대학교, [통계 학습 입문](https://www.statlearning.com) 저자

> 많은 데이터 과학 교재는 형식적인 계산을 수행하는 방법을 알려줍니다. 대신 *데이터로 이야기하기*는 분석의 사고방식과 과정에 참여하는 방법을 알려줍니다. 데이터로 의미를 만들고 이야기를 전달하는 데 필요한 계산, 통계 및 철학적 기술로 학생들을 무장시킴으로써 이 책은 독보적으로 실행 가능하고 힘을 실어주는 책으로 두각을 나타냅니다.
>
> **에밀리 리더러**, Capital One, [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/) 저자

> *데이터로 이야기하기*는 데이터를 사용하여 배우고 긍정적인 변화에 영향을 미치는 사려 깊은 가이드입니다. 이 책에는 프로세스의 각 단계가 포함되어 있으며 많은 데이터 과학자와 미래의 데이터 스토리텔러에게 오랫동안 동반자가 될 수 있습니다.
>
> **크리스토퍼 피터스**, Zapier

> 이것은 또 다른 통계 책이 아닙니다. 그보다 훨씬 낫습니다. 이것은 정량적 연구 수행, 과학적 정당화, 품질 관리, 의사소통 및 인식론적 겸손에 관한 책입니다. 모든 방법론 커리큘럼에 귀중한 보충 자료이며 자율 학습자에게도 유용합니다.
>
> **리처드 맥엘리스**, 막스 플랑크 진화 인류학 연구소, [통계적 재고찰](https://xcelab.net/rm/statistical-rethinking/) 저자

> 현명한 직업 선택은 자신의 기술이 성장하는 자원과 상호 보완적인 분야를 선택하는 것입니다. 앞으로 수십 년 동안 데이터를 분석하는 데 능숙한 사람들이 번창할 것입니다. 즉, 통계를 분석하고 설득력 있는 이야기를 전달하는 것입니다. 로한 알렉산더의 책은 두 가지 모두를 하는 데 도움이 될 것입니다.
>
> **앤드류 리**, 호주 의회 의원, [랜더미스타: 급진적인 연구자들이 세상을 바꾸는 방법](https://yalebooks.yale.edu/book/9780300236125/randomistas/) 저자

> 모든 데이터 분석가는 데이터로 이야기를 해야 하지만 전통적인 교과서는 통계적 방법에만 초점을 맞춥니다. *데이터로 이야기하기*는 데이터 수집, 의사소통 및 재현성을 포함한 전체 데이터 과학 워크플로를 가르칩니다. 이 독특한 책을 강력히 추천합니다!
>
> **이마이 코스케**, 하버드 대학교, [정량 사회 과학 입문](https://press.princeton.edu/books/quantitative-social-science) 저자

> 이것은 데이터 과학을 시작하는 모든 사람에게 현명한 조언으로 가득 찬 특별하고 훌륭한 책입니다. 개념과 코드를 혼합하면 아이디어가 즉시 구체화되고 재현 가능한 워크플로에 대한 강조는 빠르게 발전하는 분야에 환영받는 엄격함을 가져다줍니다.
>
> **데이비드 스피겔홀터 경**, 케임브리지 대학교, [통계의 예술](https://dspiegel29.github.io/ArtofStatistics/) 저자

> 데이터로 (진실된) 이야기를 하려면 멋진 통계 모델과 빅 데이터 이상의 것이 필요합니다. 일련의 매혹적인 사례 연구를 통해 로한 알렉산더는 좋은 질문을 하고, 데이터를 수집하고, 모델을 추정하고, 결과를 전달하는 방법을 가르쳐줍니다. 이 전체적인 접근 방식은 명료하고 매력적인 산문으로 설명됩니다. 페이지는 투명성과 재현성의 중요성을 강조하는 상세한 R 예제로 가득 차 있습니다. 저는 이 책을 정말 좋아하며 모든 학생에게 추천합니다.
>
> **뱅상 아렐-분독**, 몬트리올 대학교, [인과 분석 및 정량적 방법](https://www.leslibraires.ca/livres/analyse-causale-et-methodes-quantitatives-une-vincent-arel-bundock-9782760643215.html) 저자

# 서문 {.unnumbered}

이 책은 데이터로 이야기를 전달하는 데 도움을 줄 것입니다. 이 책은 관찰한 데이터를 기반으로 관심 있는 세상의 한 측면에 대한 지식을 구축하고 공유할 수 있는 토대를 마련합니다. 불 주위에 모여 작은 그룹으로 이야기를 나누는 것은 인간과 사회 발전에 중요한 역할을 했습니다[@wiessner2014embers]. 오늘날 데이터를 기반으로 한 우리의 이야기는 수백만 명에게 영향을 미칠 수 있습니다.

이 책에서는 데이터를 탐색하고, 찌르고, 밀고, 조작하고, 반죽하고, 궁극적으로 데이터의 의미를 이해하려고 노력할 것입니다. 다양한 특징이 이 책의 선택을 이끌었습니다.

제가 박사 학위를 받은 대학의 모토는 *naturam primum cognoscere rerum* 또는 대략 "사물의 본질을 먼저 배우는 것"입니다. 그러나 원래 인용문은 *temporis aeterni quoniam* 또는 대략 "영원한 시간을 위해"로 이어집니다. 우리는 이 두 가지를 모두 할 것입니다. 저는 지속적이고 재현 가능한 지식을 확립할 수 있는 도구, 접근 방식 및 워크플로에 중점을 둡니다.

이 책에서 데이터에 대해 이야기할 때 일반적으로 인간과 관련이 있습니다. 인간은 대부분의 우리 이야기의 중심에 있을 것이며 사회적, 문화적, 경제적 이야기를 할 것입니다. 특히 이 책 전체에서 사회 현상과 데이터 모두에서 불평등에 주목할 것입니다. 대부분의 데이터 분석은 있는 그대로의 세상을 반영합니다. 가장 가난한 사람들 중 다수는 이와 관련하여 이중 부담\index{data!double burden}에 직면합니다. 불리할 뿐만 아니라 그 정도를 측정하기가 더 어렵습니다. 데이터셋에 있는 사람들을 존중하는 것이 주요 관심사이며 체계적으로 데이터셋에 없는 사람들을 생각하는 것도 마찬가지입니다.

데이터는 종종 다양한 맥락과 분야에 따라 다르지만, 이를 이해하는 데 사용되는 접근 방식은 유사한 경향이 있습니다. 데이터는 또한 점점 더 글로벌해지고 있으며, 다양한 출처에서 자원과 기회를 얻을 수 있습니다. 따라서 저는 많은 분야와 지역의 예를 활용합니다.

지식이 되려면 우리의 발견은 다른 사람에게 전달되고, 이해되고, 신뢰받아야 합니다. 과학적, 경제적 발전은 다른 사람의 작업에 기반을 두어야만 이루어질 수 있습니다. 그리고 이것은 우리가 그들이 한 일을 이해할 수 있을 때만 가능합니다. 마찬가지로, 세상에 대한 지식을 창출하려면 다른 사람이 우리가 한 일, 발견한 것, 작업을 수행한 방식을 정확하게 이해할 수 있도록 해야 합니다. 따라서 이 책에서는 의사소통과 재현성에 대해 특히 규범적으로 다룰 것입니다.

정량적 작업의 질을 향상시키는 것은 엄청난 과제이지만 우리 시대의 과제입니다. 데이터는 우리 주변 어디에나 있지만 지속적인 지식은 거의 생성되지 않고 있습니다. 이 책은 작게나마 그것을 바꾸는 데 기여하기를 바랍니다.

## 독자 및 가정된 배경 지식 {.unnumbered}

이 책을 읽는 일반적인 독자는 1학년 학부 통계에 어느 정도 익숙하며, 예를 들어 회귀 분석을 실행해 본 적이 있습니다. 그러나 특정 수준을 대상으로 하는 것이 아니라 거의 모든 정량 과정과 관련된 측면을 제공합니다. 저는 학부, 대학원 및 전문가 수준에서 이 책으로 가르쳤습니다. 모든 사람은 고유한 요구 사항을 가지고 있지만 이 책의 일부 측면이 여러분에게 도움이 되기를 바랍니다.

열정과 관심은 사람들을 멀리 데려갔습니다. 그것들이 있다면 다른 것에 대해 너무 걱정하지 마십시오. 가장 성공적인 학생 중 일부는 정량적 또는 코딩 배경이 전혀 없는 학생들이었습니다.

이 책은 많은 내용을 다루지만 특정 측면에 대해 깊이 다루지는 않습니다. 따라서 *데이터 과학: 첫 번째 소개*[@timbersandfriends], *R for Data Science*[@r4ds], *통계 학습 입문*[@islr] 및 *통계적 재고찰*[@citemcelreath]과 같은 더 자세한 책을 특히 보완합니다. 이러한 책에 관심이 있다면 이 책으로 시작하는 것이 좋을 수 있습니다.

## 구조 및 내용 {.unnumbered}

이 책은 6개의 파트로 구성되어 있습니다. I) 기초, II) 의사소통, III) 수집, IV) 준비, V) 모델링, VI) 응용.

1부---기초---는 [-@sec-introduction]으로 시작하며, 이 책으로 무엇을 달성하려고 하는지, 왜 읽어야 하는지에 대한 개요를 제공합니다. @sec-fire-hose는 세 가지 작업 예를 살펴봅니다. 이들의 의도는 무슨 일이 일어나고 있는지에 대해 너무 걱정하지 않고 이 책에서 권장하는 전체 워크플로를 경험할 수 있도록 하는 것입니다. 해당 워크플로는 계획, 시뮬레이션, 수집, 모델링 및 전달입니다. 이 장의 모든 내용을 처음에 따라가지 못하는 것은 정상이지만, 코드를 직접 입력하고 실행하면서 살펴보아야 합니다. 이 책의 한 장만 읽을 시간이 있다면 해당 장을 추천합니다. @sec-reproducible-workflows는 제가 주장하는 워크플로에서 사용되는 재현성을 위한 몇 가지 주요 도구를 소개합니다. 이는 Quarto, R 프로젝트, Git 및 GitHub, 그리고 실제로 R을 사용하는 것과 같은 측면입니다.

2부---의사소통---은 서면 및 정적 의사소통을 고려합니다. @sec-on-writing은 정량적 글쓰기가 가져야 할 특징과 간결하고 정량적인 연구 논문을 작성하는 방법을 자세히 설명합니다. @sec-static-communication의 정적 의사소통은 그래프, 표 및 지도와 같은 특징을 소개합니다.

3부---수집---은 우리 세상을 데이터로 바꾸는 데 중점을 둡니다. @sec-farm-data는 측정으로 시작한 다음 데이터에 대한 우리 접근 방식을 지배하는 표본 추출의 필수 개념을 단계별로 살펴봅니다. 그런 다음 인구 조사 및 기타 정부 통계와 같이 데이터로 사용하도록 명시적으로 제공되는 데이터셋을 고려합니다. 이것들은 일반적으로 깨끗하고 잘 문서화된 사전 패키지된 데이터셋입니다. @sec-gather-data는 애플리케이션 프로그래밍 인터페이스(API) 사용, 데이터 스크래핑, PDF에서 데이터 가져오기 및 광학 문자 인식(OCR)과 같은 측면을 다룹니다. 아이디어는 데이터가 사용 가능하지만 반드시 데이터셋으로 설계된 것은 아니며 우리가 직접 가져와야 한다는 것입니다. 마지막으로 @sec-hunt-data는 우리에게 더 많은 것이 기대되는 측면을 다룹니다. 예를 들어, 실험을 수행하거나 A/B 테스트를 실행하거나 일부 설문 조사를 수행해야 할 수 있습니다.

4부---준비---는 원본, 편집되지 않은 데이터를 탐색하고 공유할 수 있는 것으로 정중하게 변환하는 방법을 다룹니다. @sec-clean-and-prepare는 데이터 정리 및 준비 작업에 접근할 때 따라야 할 몇 가지 원칙을 자세히 설명하는 것으로 시작한 다음 수행할 특정 단계와 구현할 검사를 살펴봅니다. @sec-store-and-share는 R 데이터 패키지 및 파케이 사용을 포함하여 해당 데이터셋을 저장하고 검색하는 방법에 중점을 둡니다. 그런 다음 데이터셋을 가능한 한 광범위하게 배포하는 동시에 해당 데이터의 기반이 되는 사람들을 존중할 때 고려하고 수행해야 할 사항으로 이어집니다.

5부---모델링---은 @sec-exploratory-data-analysis에서 탐색적 데이터 분석으로 시작합니다. 이것은 데이터셋을 이해하는 중요한 과정이지만 일반적으로 최종 제품에는 포함되지 않는 것입니다. 과정 자체가 목적입니다. @sec-its-just-a-linear-model에서는 데이터를 탐색하기 위한 선형 모델 사용이 소개됩니다. 그리고 @sec-its-just-a-generalized-linear-model은 로지스틱, 포아송 및 음이항 회귀를 포함한 일반화 선형 모델을 고려합니다. 또한 다단계 모델링을 소개합니다.

6부---응용---은 모델링의 세 가지 응용 프로그램을 제공합니다. @sec-causality-from-observational-data는 관찰 데이터에서 인과 관계를 주장하는 데 중점을 두고 차이-차이, 회귀 불연속성 및 도구 변수와 같은 접근 방식을 다룹니다. @sec-multilevel-regression-with-post-stratification은 사후 계층화를 사용한 다단계 회귀를 소개하며, 이는 통계 모델을 사용하여 알려진 편향에 대해 표본을 조정하는 것입니다. @sec-text-as-data는 텍스트-데이터에 중점을 둡니다.

@sec-concluding-remarks는 몇 가지 결론적인 발언을 제공하고, 몇 가지 미해결 문제를 자세히 설명하고, 몇 가지 다음 단계를 제안합니다.

::: {.content-visible unless-format="pdf"}
온라인 부록은 페이지 크기 제약으로 인해 다루기 어렵거나 인쇄된 책에 대해 합리적인 것보다 더 자주 업데이트해야 할 가능성이 있는 중요한 측면을 제공합니다.
[-@sec-r-essentials]는 이 책에서 사용되는 통계 프로그래밍 언어인 R의 몇 가지 필수 작업을 살펴봅니다. 참고 장이 될 수 있으며 일부 학생들은 책의 나머지 부분을 진행하면서 이 장으로 돌아갑니다.
[-@sec-datasets]는 평가에 유용할 수 있는 데이터셋 목록을 제공합니다.
이 책의 핵심은 Quarto를 중심으로 하지만 이전 버전인 R Markdown은 아직 중단되지 않았으며 사용할 수 있는 자료가 많습니다. 따라서 [-@sec-rmarkdown]에는 @sec-reproducible-workflows의 Quarto 관련 측면에 해당하는 R Markdown 내용이 포함되어 있습니다.
논문 세트는 [-@sec-papers]에 포함되어 있습니다. 이것들을 작성하면 관심 있는 주제에 대한 독창적인 연구를 수행하게 됩니다. 개방형 연구가 처음일 수 있지만, 자신의 질문을 개발하고 정량적 방법을 사용하여 탐색하고 결과를 전달할 수 있는 정도가 이 책의 성공 척도입니다.
[-@sec-sql]은 SQL 필수 사항에 대한 간략한 개요를 제공합니다.
[-@sec-production]은 모델 추정치와 예측을 더 널리 사용할 수 있도록 하는 방법을 고려합니다.
:::



## 교육학 및 주요 특징 {.unnumbered}

당신이 직접 해야 합니다. 자료와 코드를 직접 적극적으로 살펴보아야 합니다. @stephenking은 "[아마추어]는 앉아서 영감을 기다리고, 나머지 우리는 그냥 일어나서 일하러 간다"고 말합니다. 이 책을 수동적으로 읽지 마십시오. 제 역할은 @hamming1996 [p. 2-3]에 의해 가장 잘 설명됩니다.

> 저는 말하자면 코치일 뿐입니다. 저는 당신을 위해 1마일을 달릴 수 없습니다. 기껏해야 스타일을 논의하고 당신의 스타일을 비판할 수 있을 뿐입니다. 육상 과정이 당신에게 도움이 되려면 1마일을 달려야 한다는 것을 알고 있습니다. 따라서 이 책에서 듣고 읽는 것에 대해 신중하게 생각해야 합니다. 그렇지 않으면 이 책이 당신을 변화시키는 데 효과적이지 않을 것입니다. 그것이 분명히 목적이어야 합니다$\dots$

이 책은 밀도 높은 입문 12주 과정으로 구성되어 있습니다. 고급 독자에게 도전 과제를 제공할 만큼 충분한 자료를 제공하는 동시에 모든 독자가 숙달해야 하는 핵심 내용을 확립합니다. 일반적인 과정은 @sec-its-just-a-generalized-linear-model까지 대부분의 자료를 다루고 특정 관심 분야의 다른 장을 선택합니다. 그러나 학생들의 배경과 관심사에 따라 다릅니다.

@sec-fire-hose만큼 일찍부터 계획, 시뮬레이션, 획득, 모델링 및 전달이라는 워크플로를 갖게 되어 데이터로 설득력 있는 이야기를 할 수 있습니다. 이후 각 장에서 이 워크플로에 깊이를 더할 것입니다. 이를 통해 점점 더 정교하고 신뢰할 수 있게 말할 수 있습니다. 이 워크플로는 일반적으로 학계와 산업계 모두에서 요구되는 기술을 포함합니다. 여기에는 의사소통, 윤리, 재현성, 연구 질문 개발, 데이터 수집, 데이터 정리, 데이터 보호 및 배포, 탐색적 데이터 분석, 통계 모델링 및 확장이 포함됩니다.

이 책의 특징 중 하나는 윤리와 불평등 문제가 한 장에 모여 쉽게 무시할 수 있는 것이 아니라 전체에 걸쳐 통합되어 있다는 것입니다. 이것들은 중요하지만 그 가치를 즉시 파악하기 어려울 수 있으므로 긴밀하게 통합되어 있습니다.

이 책은 또한 잠재적인 고용주에게 보여줄 수 있는 작업 포트폴리오를 구축할 수 있도록 설계되었습니다. 업계에서 일자리를 원한다면 이것은 틀림없이 가장 중요한 일입니다. @robinsonnolis2020 [p. 55]은 포트폴리오가 자신이 할 수 있는 것을 보여주는 프로젝트 모음이며 구직에 성공하는 데 도움이 될 수 있는 것이라고 설명합니다.

소설 *마지막 사무라이*[@helendewitt p. 326]에서 한 등장인물은 다음과 같이 말합니다.

> 학자는 구절의 어떤 단어를 보더라도 그것이 나타난 다른 구절을 즉시 생각할 수 있어야 합니다. $\dots$ 그래서 텍스트는 각 단어가 눈 덮인 봉우리이고 표면 아래에 거대한 얼어붙은 상호 참조 덩어리가 있는 빙산 떼와 같았습니다.

유사한 방식으로 이 책은 독립적인 텍스트와 지침을 제공할 뿐만 아니라 전문 지식의 기반이 되는 중요한 지식 덩어리를 개발하는 데도 도움이 됩니다. 어떤 장도 마지막 말이라고 자처하지 않고 대신 다른 작업과 관련하여 작성됩니다.

수업에서 이 책을 사용하는 방법은 다양합니다. 전통적인 분필 강의도 효과가 있지만, 학생들이 수업 전에 장을 읽도록 (주간 퀴즈나 중간고사를 통해 동기를 부여하여) 할 수 있다면 수업을 그룹 기반 프로젝트와 토론에 사용하는 것이 즐겁습니다. 매주 2~4명의 학생으로 구성된 소규모 그룹을 만들고(매주 무작위로 새 그룹을 만들어 학생들이 새로운 사람들과 함께 작업할 기회를 제공합니다). 그런 다음 일반적으로 "생각-짝-공유" 연습[@lyman1981responsive]에 따라 대부분의 연습 문제를 먼저 스스로 해결한 다음 그룹과 비교하고 마지막으로 선택한 답변을 수업과 공유하도록 합니다.

시간 배분 및 범위 측면에서 1부 "기초"가 다루어지는 한 나머지 장은 상당히 독립적입니다. 첫 번째 논문은 특히 중요하며 학생들이 향후 논문에 대한 교훈을 통합할 수 있도록 신속하게 학생들에게 반환해야 합니다.

각 장에는 다음과 같은 특징이 있습니다.

-   해당 장을 읽기 전에 살펴봐야 할 필수 자료 목록입니다. 명확히 하자면, 먼저 해당 자료를 읽은 다음 이 책으로 돌아와야 합니다. 각 장에는 광범위한 참고 문헌도 포함되어 있습니다. 해당 주제에 특히 관심이 있다면 이를 추가 탐색을 위한 출발점으로 사용해야 합니다.
-   해당 장에서 개발되는 주요 개념 및 기술 요약입니다. 기술 장에는 해당 장에서 사용되는 소프트웨어 및 패키지 목록이 추가로 포함되어 있습니다. 이러한 특징의 조합은 학습 체크리스트 역할을 하며 장을 완료한 후 다시 돌아와야 합니다.
-   "연습"에서는 작은 시나리오를 제공하고 이 책에서 권장하는 워크플로를 통해 작업하도록 요청합니다. 아마 15~30분 정도 걸릴 것입니다. 미국 바이올리니스트 힐러리 한은 거의 매일 바이올린 연습, 종종 음계 또는 유사한 연습을 하는 모습을 공개적으로 문서화합니다. 비슷한 작업을 수행하는 것이 좋으며 이러한 연습은 이를 가능하게 하도록 설계되었습니다.
-   필수 자료를 살펴본 후, 하지만 장을 살펴보기 전에 지식을 테스트하기 위해 완료해야 하는 몇 가지 "퀴즈" 질문입니다. 장을 완료한 후에는 각 측면을 이해했는지 확인하기 위해 질문을 다시 살펴보아야 합니다. 답변 가이드는 요청 시 제공됩니다.
-   자료에 적극적으로 참여하도록 더욱 장려하는 "과제"입니다. 이러한 질문에 대한 답변을 논의하기 위해 소규모 그룹을 구성하는 것을 고려할 수 있습니다.

일부 장에는 추가적으로 다음과 같은 특징이 있습니다.

-   "아, 그것에 대해 좋은 데이터가 있다고 생각하시는군요!"라는 섹션은 일반적으로 흠잡을 데 없고 명확한 데이터가 있다고 가정하지만 실제로는 그렇지 않은 특정 상황에 초점을 맞춥니다.
-   "거인의 어깨 위에 서서"라는 섹션은 우리가 기반을 두고 있는 지적 토대를 만든 사람들 중 일부에 초점을 맞춥니다.


## 소프트웨어 정보 및 규칙 {.unnumbered}

이 책에서 제가 시작하는 소프트웨어는 R [@citeR]입니다.\index{R!why} 이 언어는 오픈 소스이고 널리 사용되며 전체 워크플로를 다룰 만큼 충분히 일반적이면서도 잘 개발된 기능이 많기 때문에 선택되었습니다. 이전에 R을 사용해 본 적이 없다고 가정하지 않으며, 이 책에 R을 선택한 또 다른 이유는 R 사용자 커뮤니티입니다. 이 커뮤니티는 특히 초보자를 환영하며 초보자 친화적인 보충 자료가 많이 제공됩니다.

::: {.content-visible when-format="pdf"}
프로그래밍 언어가 없다면 R은 시작하기에 좋은 언어입니다. ["R 필수 사항"](https://tellingstorieswithdata.com/20-r_essentials.html)을 꼭 살펴보십시오.
:::

::: {.content-visible unless-format="pdf"}
프로그래밍 언어가 없다면 R은 시작하기에 좋은 언어입니다. [-@sec-r-essentials]를 꼭 살펴보십시오.
:::

R에 익숙해진 후에는 또 다른 오픈 소스 프로그래밍 언어인 Python도 배우도록 권장합니다. Python은 R보다 초보자가 시작하기가 약간 덜 쉽지만 업계에서 널리 사용됩니다. 합리적인 경우 Python을 사용할 것이며, 이를 통해 R과 Python 모두에 익숙해질 것입니다.

1. R과 RStudio를 자신의 컴퓨터에 다운로드하십시오. R은 [여기](http://cran.utstat.utoronto.ca/)에서 무료로 다운로드할 수 있고, RStudio Desktop은 [여기](https://rstudio.com/products/rstudio/download/#download)에서 무료로 다운로드할 수 있습니다. 그리고 Quarto는 [여기](https://quarto.org/docs/get-started/)에서 다운로드하십시오.
2. [여기](https://posit.cloud)에서 Posit Cloud 계정을 만드십시오. 이렇게 하면 클라우드에서 R을 실행할 수 있습니다.
3. [여기](https://code.visualstudio.com)에서 VS Code를 무료로 다운로드하십시오.
4. [여기](https://colab.google)에서 Google Colab 무료 계정을 만드십시오.

패키지는 타자기 글꼴로 표시됩니다(예: `tidyverse`). 함수도 타자기 글꼴로 표시되지만 괄호가 포함됩니다(예: `filter()`).


## 저자 소개 {.unnumbered}

저는 토론토 대학교 정보 학부와 통계 과학과에 공동으로 임명된 조교수입니다. 또한 캐나다 통계 과학 연구소(CANSSI) 온타리오의 부소장, 매시 칼리지의 선임 연구원, 슈워츠 라이스만 기술 및 사회 연구소의 교수 제휴자, 데이터 과학 연구소 재현성 주제 프로그램의 공동 책임자이기도 합니다. 저는 호주 국립 대학교에서 경제사학을 전공하여 경제학 박사 학위를 받았으며, 존 탕(의장), 마틴 마리오티, 팀 해튼, 잭 워드의 지도를 받았습니다.

제 연구는 데이터 과학의 신뢰성을 향상시키는 워크플로를 개발하는 방법을 조사합니다. 특히 데이터 과학에서 테스트의 역할에 관심이 있습니다.

저는 가르치는 것을 즐기며 다양한 배경의 학생들이 데이터를 사용하여 설득력 있는 이야기를 하는 방법을 배우도록 돕는 것을 목표로 합니다. 저는 학생들이 다양한 분야에서 통계적 방법을 사용하는 데 능숙할 뿐만 아니라 그 한계를 인식하고 작업의 더 넓은 맥락에 대해 깊이 생각하도록 개발하려고 노력합니다. 저는 정보 학부와 통계 과학과에서 학부 및 대학원 수준 모두에서 가르칩니다. 저는 RStudio 공인 Tidyverse 트레이너입니다.

저는 모니카 알렉산더와 결혼했고 두 아이가 있습니다. 저는 아마 책에 너무 많은 돈을 쓰고 도서관에서 너무 많은 시간을 보낼 것입니다. 추천할 만한 책이 있다면 기꺼이 듣겠습니다.

::: {.content-visible unless-format="pdf"}

## 토지 인정 {.unnumbered}

이 책은 주로 미시소거 크레딧, 휴런-웬닷, 세네카의 전통적인 땅에서 쓰여졌습니다. 데이터는 오랫동안 억압과 해악에 사용되어 왔으며, 이 땅의 역사를 인정하는 것은 우리 자신의 데이터 사용에서 더 나아지려고 노력해야 할 필요성을 상기시켜 줍니다.

:::

## 감사 인사 {.unnumbered}

많은 분들이 이 책을 개발하는 데 도움이 된 코드, 데이터, 예제, 지도, 기회, 생각 및 시간을 아낌없이 제공해 주셨습니다.

감사합니다.
데이비드 그럽스,
커티스 힐,
로빈 로이드-스타크스,
그리고 Taylor & Francis 팀이 이 책을 편집하고 출판하며 귀중한 지도와 지원을 제공해 주셨습니다.
이 책을 철저히 편집해 주신 에리카 올로프에게 감사드립니다.
이 책의 초기 초고를 철저히 검토하고 개선을 위한 상세한 피드백을 제공해 주신 이사벨라 게멘트에게 감사드립니다.

이 책의 모든 단어를 살펴보고 많은 단어를 개선하고 이 책에서 다루는 많은 내용에 대한 제 생각을 날카롭게 하는 데 도움을 준 애니 콜린스에게 감사드립니다. 가르치는 즐거움 중 하나는 애니와 같이 재능 있는 사람들이 경력을 시작할 때 함께 일할 수 있는 기회입니다.

책의 초기 계획에 대한 자세한 의견을 제공해 주신 에밀리 리더러에게 감사드립니다. 그런 다음 초고가 완성된 후 원고로 돌아와 세세한 부분까지 살펴보셨습니다. 그녀의 사려 깊은 의견은 책을 크게 개선했습니다. 더 넓게는 그녀의 작업은 이 책의 많은 내용에 대한 제 생각을 바꾸었습니다.

저는 운 좋게도 전체 장, 때로는 두세 장 이상을 읽은 많은 검토자가 있었습니다. 그들은 정말로 그 이상을 해냈고 이 책을 개선하기 위한 훌륭한 제안을 제공했습니다. 이에 대해 저는 다음 분들께 감사드립니다.
알버트 랩,
알렉스 헤이즈,
알렉스 러스콤(경찰 폭력 "아, 그것에 대해 좋은 데이터가 있다고 생각하시는군요!" 항목도 제안),
아리엘 문도,
벤자민 하이베-카인스,
댄 라이언,
에릭 드라이스데일,
플로렌스 발레-뒤부아,
잭 베일리,
재 해트릭-심퍼스,
존 칸,
조나단 킨(파케이 전문 지식도 아낌없이 공유),
로렌 케네디(MRP에 대한 제 생각을 발전시키기 위해 코드, 데이터 및 전문 지식도 아낌없이 공유),
리암 웰시,
리자 볼튼(이 책을 어떻게 가르쳐야 하는지에 대한 제 아이디어를 발전시키는 데도 도움),
루이스 코레이아,
맷 라토,
마티아스 버거,
마이클 문,
로베르토 렌티니,
라이언 브릭스, 그리고
테일러 라이트.

많은 분들이 상황을 크게 개선한 구체적인 제안을 해주셨습니다. 이 모든 분들은 이 책이 기반을 두고 있는 오픈 소스 프로그래밍 언어 커뮤니티를 특징짓는 관대함의 정신에 기여합니다. 모든 분들께 감사드립니다.
A 마흐푸즈는 포아송 회귀를 다루는 것이 중요하다고 깨닫게 해주었습니다.
애런 밀러는 FINER 프레임워크를 제안했습니다.
앨리슨 프레스만스 힐은 워드뱅크를 제안했습니다.
크리스 워쇼는 민주주의 기금 유권자 연구 그룹 설문 조사 데이터를 제안했습니다.
크리스티나 웨이는 많은 코드 오류를 지적했습니다.
클레어 배터실은 글쓰기에 관한 많은 책으로 저를 안내했습니다.
엘라 케이는 Quarto로 전환할 것을 제안하고 당연히 주장했습니다.
파리아 칸다커는 "R 필수 사항" 장이 된 것을 제안했습니다.
하림 나비드는 업계 경험을 아낌없이 공유했습니다.
히스 프리스턴은 토론토 노숙자 데이터에 대한 지원을 제공했습니다.
제시카 그론스벨은 통계 실무에 대한 귀중한 제안을 했습니다.
켈리 치우는 텍스트-데이터의 중요성을 강조했습니다.
레슬리 루트는 "아, 그것에 대해 좋은 데이터가 있다고 생각하시는군요!"라는 아이디어를 생각해냈습니다.
마이클 총은 EDA에 대한 제 접근 방식을 형성했습니다.
마이클 도넬리, 피터 헵번, 레오 레이몽-벨질은 제가 알지 못했던 정치학, 사회학, 통계학 분야의 고전 논문에 대한 포인터를 제공했습니다.
닉 호튼은 @sec-exploratory-data-analysis에서 해들리 위컴 비디오를 제안했습니다.
폴 호제츠는 R 패키지를 만드는 방법을 가르쳐주었고 이 책의 표지 아트를 만들었습니다.
라두 크라이우는 표본 추출이 적절한 위치를 차지하도록 보장했습니다.
샬라 겔판드는 제가 R을 사용하는 방법에 대해 주장하는 접근 방식입니다.
토마스 윌리엄 로젠탈은 샤이니의 잠재력을 깨닫게 해주었습니다.
톰 카르도소와 제인 슈워츠는 언론인들이 모은 훌륭한 데이터 출처였습니다.
얀보 탕은 낸시 리드의 "거인의 어깨 위에 서서" 항목을 지원했습니다.
마지막으로 크리스 매디슨과 마이아 발린트는 맺음 시를 제안했습니다.

박사 과정 지도 위원회인 존 탕, 마틴 마리오티, 팀 해튼, 잭 워드에게 감사드립니다. 그들은 제가 관심 있는 지적 공간을 탐색할 자유, 그러한 관심사를 추구할 지원, 그리고 그 모든 것이 가시적인 결과로 이어지도록 하는 지도를 제공했습니다. 그 기간 동안 배운 것이 이 책의 기초가 되었습니다.

이 책은 크리스 베일, 스콧 커닝햄, 앤드류 하이스(이 책이 나오기 훨씬 전에 이 책과 같은 이름의 과정을 독립적으로 가르쳤음), 리사 렌드웨이, 그랜트 맥더못, 네이선 마티아스, 데이비드 밈노, 에드 루빈 등 다른 사람들의 온라인에서 무료로 제공되는 노트와 교재로부터 큰 도움을 받았습니다. 이분들께 감사드립니다. 학자들이 자신의 자료를 온라인에서 무료로 제공하는 변화된 규범은 훌륭하며, 이 책의 무료 온라인 버전([여기](https://tellingstorieswithdata.com/))이 이에 기여하기를 바랍니다.

일부 평가 항목 개발에 도움을 주신 사만다-조 카에타노에게 감사드립니다. 또한 일부 채점 기준을 적용할 수 있도록 허락해 주신 리사 롬키와 앨런 총에게도 감사드립니다. @sec-on-writing 튜토리얼의 일부 측면에 대한 촉매제는 @draftnumberfour [p. 186]와 첼시 팔렛-펠레리티였습니다. "대화형 커뮤니케이션" 튜토리얼의 아이디어는 마우리시오 바르가스 세풀베다("파차")와 앤드류 휘트비의 작업이었습니다.

다음 분들의 수정에 감사드립니다.
에이미 패로우,
아르시 라칸팔,
세자르 비야레알 구즈만,
클로이 티어스타인,
핀 코롤-오드와이어,
플라비아 로페즈,
그레고리 파워,
홍시,
정재든,
존 헤이즈,
조이스 쉬안,
로라 클라인,
로레나 알마라즈 데 라 가르자,
매튜 로버트슨,
미카엘라 드루이야르,
무니카 타남,
림 알라사디,
롭 짐머만,
타예자 치쿰비리케,
위즈단 타리크,
양우, 그리고
한예원.

켈리 라이언스는 지원, 지도, 멘토링 및 우정을 제공했습니다. 매일 그녀는 학자가 어떠해야 하는지, 더 넓게는 한 사람으로서 무엇을 지향해야 하는지를 보여줍니다.

그렉 윌슨은 교육에 대해 생각할 수 있는 구조를 제공하고 "척도" 스타일 연습을 제안했습니다. 그는 이 책의 촉매제였으며 초고에 유용한 의견을 제공했습니다. 매일 그는 지적 공동체에 기여하는 방법을 보여줍니다.

팬데믹 기간 동안 첫째 아이, 그리고 둘째 아이를 돌보며 이 책을 쓸 수 있게 해준 엘 코테에게 감사드립니다.

2021년 크리스마스 현재 이 책은 부분적으로 완성된 노트의 이질적인 모음이었습니다. 모든 것을 버리고 두 달 동안 세계 반대편에서 와서 모든 것을 다시 쓰고 일관된 초고를 만들 기회를 주신 엄마와 아빠께 감사드립니다.

캔버라에서 2주간의 "글쓰기 수련회"를 후원해 주신 마리야 타플라가와 ANU 호주 정치 연구 센터 정치 및 국제 관계 학교에 감사드립니다.

마지막으로 모니카 알렉산더에게 감사드립니다. 당신이 없었다면 저는 책을 쓰지 못했을 것입니다. 가능하다고 생각조차 하지 못했을 것입니다. 이 책의 가장 좋은 아이디어 중 다수는 당신의 것이며, 그렇지 않은 아이디어는 당신이 모든 것을 여러 번 읽음으로써 더 좋게 만들었습니다. 이 책을 쓰는 데 헤아릴 수 없는 도움을 주시고, 그 기반을 제공해 주시고(도서관에서 R에서 특정 행을 가져오는 방법을 여러 번 보여준 것을 기억합니다!), 글을 쓸 시간을 주시고, 어제 완벽했던 것을 끝없이 다시 쓰는 것이 책을 쓰는 것이라는 사실이 밝혀졌을 때 격려해 주시고, 이 책의 모든 것을 여러 번 읽어주시고, 적절하게 커피나 칵테일을 만들어 주시고, 아이들을 돌봐주시고, 그 외에도 많은 것에 대해 감사드립니다.

rohan.alexander@utoronto.ca로 저에게 연락할 수 있습니다.

::: {style="text-align: right;"}
로한 알렉산더
토론토, 캐나다
2023년 5월
:::


\mainmatter
