[workspace]
authors = ["Taeyoon Kim <deepthought@postech.ac.kr>"]
channels = ["conda-forge"]
name = "telling-stories-with-data"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-r-packages = "R -e 'install.packages(c(\"opendatatoronto\", \"datasauRus\", \"troopdata\", \"rdrobust\", \"analogsea\", \"AustralianPoliticians\", \"dataverse\", \"nflverse\"), repos=\"https://cloud.r-project.org/\", Ncpus=Sys.getenv(\"NCPUS\", \"1\"))'"
install-r-github-packages = "R -e 'options(Ncpus=Sys.getenv(\"NCPUS\", \"1\")); devtools::install_github(c(\"ttimbers/canlang\", \"sharlagelfand/astrologer\"))'"
render = { cmd = "quarto render mybook --to html", env = { RETICULATE_USE_UV = "false", RETICULATE_MINICONDA_ENABLED = "false" } }

[dependencies]
quarto = ">=1.7.32,<2"
r-base = ">=4.4.3,<4.5"
r-essentials = ">=4.4,<5"
r-janitor = ">=2.2.1,<3"
r-knitr = ">=1.50,<2"
r-lubridate = ">=1.9.4,<2"
r-tidyverse = ">=2.0.0,<3"
r-s2 = ">=1.1.7,<2"
r-units = ">=0.8_5,<0.9"
r-sf = ">=1.0_20,<2"
r-classint = ">=0.4_11,<0.5"
cmake = ">=4.0.3,<5"
udunits2 = ">=2.2.28,<3"
r-tinytable = ">=0.10.0,<0.11"
r-here = ">=1.0.1,<2"
r-arrow = ">=19.0.1,<20"
r-aer = ">=1.2_15,<2"
r-gitcreds = ">=0.1.2,<0.2"
r-lintr = ">=3.2.0,<4"
r-renv = ">=1.1.4,<2"
r-styler = ">=1.10.3,<2"
r-usethis = ">=3.1.0,<4"
r-babynames = ">=1.0.1,<2"
r-ggmap = ">=4.0.1,<5"
r-leaflet = ">=2.2.2,<3"
r-mapdeck = ">=0.3.5,<0.4"
r-mapproj = ">=1.2.12,<2"
r-modelsummary = ">=2.4.0,<3"
r-patchwork = ">=1.3.1,<2"
r-tidygeocoder = ">=1.0.5,<2"
r-wdi = ">=2.7.9,<3"
r-cancensus = ">=0.5.7,<0.6"
r-devtools = ">=2.4.5,<3"
r-tidycensus = ">=1.7.1,<2"
r-pdftools = ">=3.5.0,<4"
r-spotifyr = ">=2.2.5,<3"
r-mice = ">=3.17.0,<4"
r-naniar = ">=1.1.0,<2"
r-poissonreg = ">=1.0.1,<2"
r-tidymodels = ">=1.3.0,<2"
"r-broom.mixed" = ">=0.2.9.6,<0.3"
r-palmerpenguins = ">=0.1.1,<0.2"
r-reticulate = ">=1.42.0,<2"
python = ">=3.12"
polars = "*"
numpy = "*"
matplotlib = "*"
seaborn = "*"
pydantic = "*"
pyarrow = "*"
r-tidytext = ">=0.4.2,<0.5"
r-collapse = ">=2.1.6,<3"
r-boot = ">=1.3_32,<2"
r-haven = ">=2.5.5,<3"
r-labelled = ">=2.16.0,<3"
r-broom = ">=1.0.12,<2"
r-marginaleffects = ">=0.32.0,<0.33"
r-gutenbergr = ">=0.4.1,<0.5"
r-tidybayes = ">=3.0.7,<4"
r-estimatr = ">=1.0.6,<2"
r-matchit = ">=4.7.2,<5"
r-plumber = ">=1.3.3,<2"
r-rstanarm = ">=2.32.2,<3"
r-gt = ">=1.3.0,<2"
r-magick = ">=2.8.6,<3"
