---
engine: knitr
---

# 칵테일 {#sec-cocktails}

각 챕터는 모니카가 만든 칵테일에서 영감을 받았습니다. (대부분의) 이름은 라디오헤드 노래입니다.

**1장---데이터로 이야기하기**

*모든 것이 제자리에*

바카디 슈페리어 1 oz
라임 주스 1/2 oz
망고 시럽 1/2 oz
샴페인 1 oz

**2장---소방 호스에서 마시기**

*강에 뛰어들었는데 무엇을 보았을까?*

헤네시 2 oz
레몬 주스 1 oz
딸기 시럽 1 oz
소다수 채우기

**3장---재현 가능한 워크플로우**

*알람도 놀라움도 없이*

엠프레스 진 1 1/2 oz
생 제르맹 1/2 oz
라임 주스 1/2 oz
라즈베리 시럽 1/4 oz
앙고스투라 비터스 한 방울

**4장---연구 글쓰기**

*감상적으로 되지 마라, 항상 헛소리로 끝난다*

헤네시 1 oz
그랑 마르니에 1/2 oz
아마로 노니노 1/2 oz
레몬 주스 1/4 oz
꿀 시럽 1/4 oz
체리 가니쉬

**5장---정적 커뮤니케이션**

*제자리를 찾아가는 직소 퍼즐*

불릿 라이 1 oz
레몬 주스 1 oz
그린 샤르트뢰즈 1 oz
생 제르맹 1/2 oz
룩사르도 마라스키노 오리지널 1/2 oz
앙고스투라 비터스 한 방울
레모네이드 채우기

**6장---데이터 수집 (Farm data)**

*네온사인 속에서; 위아래로 스크롤*

불릿 라이 1 1/4 oz
그랑 마르니에 1/2 oz
레몬 주스 3/4 oz
오렌지 주스 3/4 oz
그레나딘 1/2 oz
라즈베리 시럽 1/4 oz

**7장---데이터 수집 (Gather data)**

*1월에 4월 소나기*

버팔로 트레이스 버번 2 oz
갈리아노 바닐라 1 oz
라즈베리 시럽 1 oz
레몬 주스 1 oz
앙고스투라 비터스 한 방울

**8장---데이터 사냥 (Hunt data)**

*여기 나는 살아있다, 항상 모든 것이*

릴레 2 oz
코인트로 1 oz
토닉 2-3 oz

**9장---데이터 정리 및 준비**

*인프라가 붕괴될 것이다*

체리 주입 보드카 (아이스버그) 1 1/2 oz
스위트 베르무트 1 oz
라즈베리 시럽 1 oz
라임 주스 1 oz
앙고스투라 비터스 한 방울

**10장---저장 및 공유**

*그리고 당신은 잘못된 곳을 보고 있다는 것을 깨닫는다*

포 로지스 버번 1 1/4 oz
사과 사이다 1 oz
그랑 마르니에 1/2 oz
아마레토 1/4 oz
레몬 주스 1/2 oz
생강 시럽 1/2 oz
앙고스투라 비터스 한 방울

**11장---탐색적 데이터 분석**

*느낀다고 해서 그것이 거기에 있다는 의미는 아니다*

글린네반 캐나다 위스키 1 1/2 oz
스위트 베르무트 3/4 oz
베네딕틴 3/4 oz
압생트 한 방울
페이쇼 비터스 두 방울
앙고스투라 비터스 두 방울

**12장---선형 모델**

*최선을 다할 수 있다면, 그 최선으로 충분하다*

불릿 라이 2 oz
스위트 베르무트 1 oz
블랙베리 시럽 1/2 oz
앙고스투라 비터스 한 방울

**13장---일반화 선형 모델**

*그들은 우리를 대변하지 않는다*

캡틴 모건 다크 럼 1 1/2 oz
꿀 시럽 1 oz
레몬 주스 1 oz
생강 시럽 1/2 oz
피 브라더스 올드 패션드 비터스 한 방울
체리 가니쉬

**14장---관찰 데이터에서 인과 관계**

*우리는 언제든 일어날 수 있는 사고이다*

헤네시 1 1/2 oz
코인트로 3/4 oz
베르주 3/4 oz
심플 시럽 1 바스푼
레몬 가니쉬

**15장---사후 계층화 다단계 회귀**

*조금씩, 어떻게든*

캡틴 모건 다크 럼 1 1/2 oz
사탕수수 시럽 3/4 oz
레몬 주스 1/2 oz
오렌지 주스 1/2 oz
생강 시럽 1/2 oz
올드 패션드 비터스 한 방울

**16장---데이터로서의 텍스트**

*단어는 무딘 도구이다; 단어는 잘린 산탄총이다*

버팔로 트레이스 버번 2 oz
룩사르도 마라스키노 오리지널 1/4 oz
설탕 조각 1개
앙고스투라 비터스 한 방울
압생트 한 방울
체리 가니쉬

**17장---결론**

*나는 다음 막, 무대 뒤에서 기다리고 있다*

플리머스 진 1 oz
레몬 주스 1/2 oz
생 제르맹 1/2 oz
앙고스투라 비터스 한 방울
샴페인 채우기

**부록 A---R 필수**

*중력은 항상 이긴다*

버팔로 트레이스 버번 2 oz
스위트 베르무트 1 oz
체리 시럽 1 1/2 oz
레몬 주스 1 1/2 oz
피 브라더스 올드 패션드 비터스 한 방울

**부록 B---데이터셋**

TBD

**부록 C---R 마크다운***

TBD

**부록 D---논문***

TBD

**부록 E---상호작용***

TBD

**부록 F---데이터시트***

TBD

**부록 G---SQL***

TBD

**부록 H---예측***

*2+2는 항상 5가 된다*

TBD

**부록 I---생산***

*사랑의 관심은 필요 없다*

봄베이 사파이어 진 1 3/4 oz
으깬 오이에 10분간 얼음과 함께 담가둔 릴레 블랑 1 oz
베네딕틴 1/4 oz
앙고스투라 2 방울
저어주고 걸러냄
선택 사항: 신선한 보리지로 장식

**부록 J---수업 활동***

TBD
