project:
  type: book
  output-dir: ../docs/mybook # Adjusted output directory

book:
  title: "데이터로 이야기하기" # Korean Title
  subtitle: "R과 Python을 활용한 애플리케이션과 함께" # Korean Subtitle
  author: "Rohan Alexander" # Author remains the same
  date: "2023년 7월 27일" # Date in Korean format - I'll use the original date for now, can be updated
  search: true
  cover-image: ../figures/tellingstorieswithdatapainting.png # Adjusted path
  repo-url: https://github.com/RohanAlexander/telling_stories/ # Repo URL can remain same or point to a Korean-specific fork if it exists
  repo-actions: [edit]
  site-url: https://tellingstorieswithdata.com/mybook # Adjusted site URL
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index_ko.qmd # Korean version of index
    - 00-errata_ko.qmd # Korean version
    - part: "기초" # Korean "Foundations"
      chapters:
        - 01-introduction_ko.qmd
        - 02-drinking_from_a_fire_hose_ko.qmd
        - 03-workflow_ko.qmd
    - part: "소통"  # Korean "Communication"
      chapters:
        - 04-writing_research_ko.qmd
        # Add other Korean chapter files here as they are translated
        # - 05-graphs_tables_maps_ko.qmd
    # Add other parts and chapters in Korean as they become available
    # For now, I will only list the files that were moved.
    # The user can add more later.

# Appendices can be added later if translated
#  appendices:
#    - 20-r_essentials_ko.qmd

crossref:
  appendix-title: "온라인 부록" # Korean "Online Appendix"

bibliography: ../references.bib # Adjusted path

format:
  html:
    theme:
      - cosmo
      - ../custom.scss # Adjusted path
    callout-appearance: simple
  # PDF settings can be adjusted if a Korean-specific latex setup is available
  # pdf:
  #   documentclass: krantz
  #   include-in-header: ../latex/preamble.tex
  #   include-before-body: ../latex/before_body.tex
  #   include-after-body: ../latex/after_body.tex
  #   keep-tex: true
  #   callout-appearance: simple

# Add language setting for Korean
lang: ko
