name: Render Quarto PDFs and Release

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build-quarto-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Noto CJK Fonts and set locale
        run: |
          sudo apt-get update
          sudo apt-get install -y a--no-install-recommends fonts-noto-cjk fontconfig locales
          sudo rm -rf /var/lib/apt/lists/*

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Add Quarto and Font packages to Pixi environment
        timeout-minutes: 180 # 예: 3시간 (기본값은 360분, 즉 6시간)
        run: |
          pixi install
          pixi run install-r-packages
          pixi run install-r-github-packages

      - name: Install TinyTeX via Quarto
        run: |
          pixi run quarto install tool tinytex

      - name: Update TinyTeX font cache
        run: |
          sudo fc-cache -fv

      - name: Render Quarto book to PDF
        run: |
          cd mybook
          pixi run quarto render --to pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarto-pdf-book
          path: mybook/_book/데이터로-이야기하기.pdf

  create-release:
    needs: build-quarto-book
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: quarto-pdf-book
          path: .

      - name: Get current date for release tag
        id: date
        run: echo "date=$(date +'%Y.%m.%d-%H%M')" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}-v${{ github.run_number }}-${{ steps.date.outputs.date }}
          name: Release ${{ github.ref_name }} v${{ github.run_number }} (${{ steps.date.outputs.date }})
          body: Automated release of Quarto PDF book for commit ${{ github.sha }}.
          files: 데이터로-이야기하기.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}